esphome:
  name: homeenergymeter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !? $env.esp_api_password

ota:
  password: !? $env.esp_ota_password 

mqtt:
  broker: !? $env.mqtt_broker
  username: !? $env.mqtt_username
  password: !? $env.mqtt_password
  discovery: True

wifi:
  ssid: !? $env.wifi_ssid
  password: !? $env.wifi_password
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EnergyMeter"
    password: !? $env.wifi_ap_password

sensor:
  - platform: pulse_meter
    pin: GPIO013
    unit_of_measurement: 'kW'
    name: 'Electricity Usage'
    filters:
      - multiply: 0.06  # (60s/1000 pulses per kWh)
    total:
      name: "Electricity Total"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001

